version: '3.8'

services:
  snort3:
    image: cisco/snort3
    container_name: snort_ids
    network_mode: "host"
    volumes:
      - ./config:/etc/snort/rules
      - ./logs:/var/log/snort
    # We run Snort in "Alert to Console" mode so you can see hits in real-time
    command: snort -c /etc/snort/rules/local.rules -R /etc/snort/rules/local.rules -A console -i eth0
    stdin_open: true
    tty: true