name: Snort Rule Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-rules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Snort Syntax Check
        run: |
          # Use the public jasonish/snort image to avoid pull access errors
          docker run --rm -v ${{ github.workspace }}/config:/etc/snort/rules \
          jasonish/snort snort -c /etc/snort/rules/local.rules -T